{
 "title": "SpeedTest Server",
 "refresh": "5s",
 "panels": [
  {
   "title": "Ping Requests Total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "ping_requests_total" }
   ]
  },
  {
   "title": "Downloaded Bytes Total",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "download_bytes_total" }
   ]
  },
  {
   "title": "Uploaded Bytes Total",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "upload_bytes_total" }
   ]
  }
 ]
}